# Generated by Django 5.0.6 on 2024-05-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_phone_body_alter_phone_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Products',
        ),
    ]
